### ISSUE TITLE
求问贵系乱序版本的性能评分和主频

### ISSUE THREAD

**Issue by NorbertZheng** [trivialmips/nontrivial-mips#2]
想请教大佬们个问题，求问贵系乱序版本的性能评分和主频。看了贵系和去年西工大的设计，不知道乱序可不可行啊，如果可以分享一些遇到的问题，将不胜感激！

**Comment by miskcoo** [comment]
@Fassial 我们没有测乱序的性能分，主频当时应该能有50~70M。不过我们的乱序版本并没有花太多时间调过，应该有很多可以优化的地方。如果是这个项目下面那个乱序版本肯定不如最终顺序的版本，甚至CPI都不如，这主要是我没有去处理内存读写的冲突而是采用直接等待的办法，事实上有更好的办法，不过这样频率可能会上不去，在比赛的“主频+CPI”的评分标准下不一定会更好。你可以问问西工大，他们最终版本是乱序的。

**Comment by NorbertZheng** [comment]
@miskcoo 明白了，多谢大佬！

**Comment by miskcoo** [comment]
然后关于启动系统方面的问题，CP0注意要严格符合标准，特别是TLB的几个异常入口会有细微的区别。另外就是注意一下中断的处理，不要在气泡处相应中断不然可能会导致EPC=0而没法返回。其它细节我也记得不太清楚了。

**Comment by NorbertZheng** [comment]
嗯，我在设计的时候会注意，多谢大佬。
